### ISSUE TITLE
File ignored for no reason

### ISSUE THREAD

**Issue by RickBradford** [mbuscemi/elm-lens#10]
In the Poolshots app, the Balls.elm file is not parsed.

Invite sent to 'mbuscemi' to investigate.

**Comment by mbuscemi** [comment]
The failure is happening at the elm-syntax level. When I run the file through my thin wrapper over elm-syntax (https://ellie-app.com/fwqbhnLQZa1/1), I get the error: `Could not continue parsing on location (103,-1)`.

I will do some digging into what this message from elm-syntax means and open a bug in that project, if applicable.

I happened to notice that elm-syntax can parse the file correctly if I apply elm-format to it.

From my perspective as the maintainer of Elm Lens, I have the following advice:
- You'll get the best results with Elm Lens when you use elm-format. In Atom, there's a plugin that will automatically format all your files on every save (https://atom.io/packages/elm-format), and I developed Elm Lens to play nice with it (the format happens first, then the text gets sent to Elm Lens for parsing).
- Put type signatures on all top-level expressions. Elm Lens can't count implied type references.

**Comment by mbuscemi** [comment]
Found it. It's the lack of a space in `specialBalls : List(String,Ball)` on line 104. When I add the space between `List` and the initial parenthesis, elm-syntax parses correctly.

**Comment by mbuscemi** [comment]
Here's the issue I created in the elm-syntax project: https://github.com/stil4m/elm-syntax/issues/5

**Comment by mbuscemi** [comment]
Mats has fixed this in version 3.1.3 of elm-syntax. I will update to this version in the 0.2.0 release of Elm Lens.

**Comment by mbuscemi** [comment]
@RickBradford Can you please confirm that this is fixed for you in v0.2.0?

**Comment by RickBradford** [comment]
Everything is working fine for me right now, have just upgraded to v0.2.0. 

However, I haven’t gone back to recreate the error to check this particular situation.

Many thanks for your work on this.
