### ISSUE TITLE
FontAwesome icons do not load for some users

### ISSUE THREAD

**Issue by mbuscemi** [mbuscemi/elm-lens#12]
`Failed to load resource: net::ERR_FILE_NOT_FOUND`
`fontawesome-webfont.woff2`, `fontawesome-webfont.woff`, `fontawesome-webfont.ttf`
reported by @halohalospecial

**Comment by mbuscemi** [comment]
Some good progress here. With the help of the Atom console, I've discovered that my fontawesome font files are actually loading from `atom://file-icons/fonts/` and not from `atom://elm-lens/resources`. It appears that registration of that internal Atom URL is not automatic.

**Comment by mbuscemi** [comment]
The default FontAwesome installation has a version number appended to the font URLs, presumably for caching optimization. This was thwarting Atom's ability to use the URL properly. I stripped those out of the URLs and was then able to load Elm Lens's version of the font files.

Fix coming 0.3.0.

**Comment by mbuscemi** [comment]
Should be fixed in 0.3. @halohalospecial, please let me know if you're still experiencing this.

**Comment by halohalospecial** [comment]
Thanks for the fix!  It's already working :tada:

**Comment by mbuscemi** [comment]
Awesome! I'm glad it's working for you.
