### ISSUE TITLE
Import using 'as' format not picked up

### ISSUE THREAD

**Issue by RickBradford** [mbuscemi/elm-lens#19]
module Table imports another module using the 'as' notation

`import Shots as S`

...the module then uses a function from that module...

`processShots yndex m = S.process yndex m`

Viewing the Shots module in elm-lens shows the function 'process' to have 0 external calls

**Comment by mbuscemi** [comment]
I just added this test to my 0.3 branch: https://github.com/mbuscemi/elm-lens/blob/0.3/elm/tests/FileMarkup/AliasedExternalReference.elm

@RickBradford This passes with the current code, meaning I am unable to reproduce the bug you describe, at least with the minimal example I created for this test. Are you able to give me access to the project where you are seeing this issue? Alternatively, can you create your own minimal example that demonstrates the bug?

**Comment by RickBradford** [comment]
Sorry, just had a major issue with my repo, will have to spend a couple of days trying to restore this project, will let you know if I can reproduce the error.

**Comment by RickBradford** [comment]
OK, recreated.

(This is the same project I gave you access to earlier, called "poolshots")

ShotModule line 26

`import Balls as B`

ShotModule line 252

`B.cbToOb bls |> traced solidLine`

Balls.elm line 30

```
cbToOb : List String -> Path
cbToOb bls = .....
```

But this function is marked as 0 internal references | 0 external references

Ditto for a very similar f unction 'obToPok' on line 39

**Comment by RickBradford** [comment]
Actually, I decided to run elm-analyse, which did an elm-format on the Balls.elm file,  and the functions are now picked up correctly.

So I can't help pinpoint the issue right now, but given my sloppy coding style, I'm sure there will be further opportunities.

**Comment by mbuscemi** [comment]
I recommend getting this plugin for Atom: https://atom.io/packages/elm-format. It will auto format every time you save. I was a little skeptical myself at first, but once I started using it, I was glad to not have to think about formatting anymore.

**Comment by RickBradford** [comment]
I have the plugin, but as is the case for many users, the plug-in can not find the requisite executable binary. There is an (unanswered) Github issue on this very topic.
