### ISSUE TITLE
Lens shows up on wrong line. Abandonware?

### ISSUE THREAD

**Issue by Erudition** [mbuscemi/elm-lens#25]
The lens lines are showing up randomly, rather than above function headers they are in the middle of functions, and they are far from the functions they describe. 

Since this project was last worked on 2 years ago and makes no mention of Elm 0.19, am I to assume it's abandonware?

**Comment by mbuscemi** [comment]
I will not support Elm 0.19.

**Comment by Erudition** [comment]
Interestingly, the headers actually do appear correctly with certain zoom levels.

Sorry to hear the project won't be supporting modern Elm. It's pretty cool.
