### ISSUE TITLE
VSCode Integration?

### ISSUE THREAD

**Issue by cruhl** [mbuscemi/elm-lens#4]
Awesome project!

I just wanted to see if you had any opinions around the feasibility of a VSCode version of this tool?

Thanks 👏

**Comment by mbuscemi** [comment]
Porting this one will be a little more involved than Elm Test Runner. The biggest hurdle will be reproducing the behavior of `decorateMarker` on an Atom `TextEditor` object, if that is even possible. There are a few other integration points, such as tooltip popups and other editor interactions that I am more confident would exist in VS.

The plan is to get all major feature work done before I port to VS Code.

**Comment by mbuscemi** [comment]
Duplicate of #11.
